
/*
List of all tables -
SELECT * FROM USER_PROFILE;
SELECT * FROM GEOPLACES;
SELECT * FROM RATING;
SELECT * FROM CUISINE;
SELECT * FROM PARKING;
*/


-- Which City has highest no of restaurants with higher rating
SELECT COUNT(R.RATING),G.CITY
FROM USER_PROFILE UP,
RATING R,
GEOPLACES G
WHERE UP.USERID = R.USERID
AND R.PLACEID = G.PLACEID
AND G.CITY != 'Not Recorded'
GROUP BY G.CITY
HAVING MAX(R.RATING) = 2 --- 2 being the highest rating
ORDER BY COUNT(R.RATING) DESC;


-- Does Parking lot affect the rating
SELECT P.PARKING_LOT,R.RATING, COUNT(R.RATING) AS "TOTAL RATING"
FROM USER_PROFILE UP,
RATING R,
GEOPLACES G,
PARKING P
WHERE UP.USERID = R.USERID
AND R.PLACEID = G.PLACEID
AND G.PLACEID = P.PLACEID
GROUP BY P.PARKING_LOT,R.RATING
ORDER BY COUNT(R.RATING) DESC
LIMIT 5;